### ISSUE TITLE
[Compilation failure] error: invalid conversion

### ISSUE THREAD

**Issue by Fincer** [spillerrec/qt-flif-plugin#5]
I'm trying to compile this on Arch Linux (qt5-base & make installed). However, the compilation fails with the following output:

> ...
> In file included from src/FlifPlugin.cpp:28:0:
> src/Flif++.hpp: In member function ‘void FlifDecoder::setCallback(uint32_t (*)(int32_t, int64_t))’:
> src/Flif++.hpp:82:45: error: invalid conversion from ‘uint32_t (*)(int32_t, int64_t) {aka unsigned int (*)(int, long int)}’ to ‘callback_t {aka unsigned int (*)(callback_info_struct*, void*)}’ [-fpermissive]
>     { flif_decoder_set_callback( d, callback ); }
>                                              ^
> src/Flif++.hpp:82:45: error: too few arguments to function ‘void flif_decoder_set_callback(FLIF_DECODER*, callback_t, void*)’
> ...

**Comment by spillerrec** [comment]
FLIF must have changed its API (it is not stable), but it doesn't look too bad. I will try to fix it tomorrow. If you use the `flif-git` package, you could try the stable `flif` package instead if you are in a hurry.

**Comment by Fincer** [comment]
Thanks for fast response!

Yeah it works with `flif` 0.2.2. I was using `flif-git` package which eventually broke things.

**Comment by spillerrec** [comment]
I got a bit lazy since you got it working and didn't end up looking on it before now, and actually the changes were related to progressive decoding which isn't used (as Qt doesn't support it). So all I had to do was to out-comment those two lines, sorry it took so long...
